### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/doc2pen#56] opened 2020-08-13 12:42 UTC
- [ ]  A video of the Doc2Pen in optimized format (For any Problems just feel free to contact me)
- [x]  Add a button to "Check out  Editor"
- [ ]  Adding Features in a better format with illustrations
- [ ] Experiment with Replacing video with a zoomed gif effect (Example given below)
- [ ] Improve the content  on the page
- [ ] Work on the dark mode

**Comment by shankhanil007** [comment] 2020-08-13 15:11
I want to work on "Add a button to Check out Editor" issue!

**Comment by Aniruddhmuley2001** [comment] 2020-08-13 18:06
@anushbhatia In the third point, do Features refer to the overall page or any specific part?

**Comment by smaranjitghose** [comment] 2020-08-14 02:41
> @anushbhatia In the third point, do Features refer to the overall page or any specific part?

It's basically about the project itself like:
- We have custom handwritten fonts
- Options to Change Pages
- Export to pdf,word,etc
- And so on

Basically like a landing page of a product that gives pictorial insights

**Comment by Aniruddhmuley2001** [comment] 2020-08-14 03:50
@smaranjitghose  Can this be assigned to multiple people? If so, I would like to work on this issue.

**Comment by smaranjitghose** [comment] 2020-08-14 04:01
> @smaranjitghose Can this be assigned to multiple people? If so, I would like to work on this issue.

Definitely, we would like the participants to work at one subtask at time. "Divide and Conquer"

**Comment by AshutoshDash1999** [comment] 2020-08-15 04:16
@smaranjitghose about the video, do you want to create a tutorial like thing for doc2pen?

**Comment by shankhanil007** [comment] 2020-08-15 06:56
Regarding "Add a button to Check out Editor" issue do I need to add a button in the home page linked to editor.html page? Is that what the issue is all about?

**Comment by smaranjitghose** [comment] 2020-08-15 08:42
> @smaranjitghose Regarding "Add a button to Check out Editor" issue do I need to add a button in the home page linked to editor.html page? Is that what the issue is all about?

Ya, that's precisely what we need. If you can put some animation to the button that will be cool!

**Comment by shankhanil007** [comment] 2020-08-15 20:06
@smaranjitghose There is already a button on the navbar of home page with "Editor" name on it and linked to editor.html page.
So what do I have to do? Add a new button?

![Editor Button](https://user-images.githubusercontent.com/58778597/90320676-c567f380-df60-11ea-99e4-69e48d55eb20.PNG)

**Comment by anushbhatia** [comment] 2020-08-16 16:00
editor button on the home page

**Comment by srishtij2000** [comment] 2020-08-17 10:16
I can work on adding features in better format

**Comment by smaranjitghose** [comment] 2020-08-18 00:38
> I can work on adding features in better format

Sure! You can improve the design

**Comment by srishtij2000** [comment] 2020-08-18 09:30
Okay

**Comment by srishtij2000** [comment] 2020-08-18 14:44
![home](https://user-images.githubusercontent.com/64734684/90527655-65a35f80-e18f-11ea-93f4-4d8bf2302b96.png)

**Comment by srishtij2000** [comment] 2020-08-19 07:24
Kindly review it

**Comment by anushbhatia** [comment] 2020-08-21 08:17
Anybody wants to work with the video in homepage we want a style like this where video will be placed on left and the right will have a button to check out the editor with some basic description.

refer this  https://autovaidya.smaranjitghose.codes/

For more clarity feel free contact me on slack

**Comment by srishtij2000** [comment] 2020-08-24 15:57
I have sent a PR so kindly review it

**Comment by anushbhatia** [comment] 2020-08-26 08:11
PR had no file change

**Comment by nikita-1801** [comment] 2020-08-31 21:15
> Anybody wants to work with the video in homepage we want a style like this where video will be placed on left and the right will have a button to check out the editor with some basic description.
> 
> refer this https://autovaidya.smaranjitghose.codes/
> 
> For more clarity feel free contact me on slack

I'd like to work on this.

**Closed** 2020-09-09 06:37 UTC
Labels: CH-20, enhancement
