### ISSUE TITLE
Position X and Y axis sliders as per given UI

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#184] opened 2020-09-29 12:07 UTC

**Comment by carbseater** [comment] 2020-12-26 14:47
I'm interested
Like the X slider horizontally and Y slider vertically ?

**Comment by smaranjitghose** [comment] 2020-12-26 14:48
> I'm interested
> Like the X slider horizontally and Y slider vertically ?

Yes

**Comment by carbseater** [comment] 2020-12-26 16:39
Hey, i'm having a problem in running the code locally like when i open the editor.html file in chrome the output window does not show up ? And is this the right place to ask these questions @smaranjitghose ? And i have figured out the positioning but not sure how it will look after loading the output window(because it's not showing up)

**Comment by smaranjitghose** [comment] 2020-12-26 17:06
> Hey, i'm having a problem in running the code locally like when i open the editor.html file in chrome the output window does not show up ? And is this the right place to ask these questions @smaranjitghose ? And i have figured out the positioning but not sure how it will look after loading the output window(because it's not showing up)
> ![Capture](https://user-images.githubusercontent.com/59422042/103155581-364cd100-47c7-11eb-9fe2-8255f5630edf.JPG)

Ya, sure you can put your queries here.
We are using p5.js for loading the canvas. Could please check if that's working

**Comment by carbseater** [comment] 2020-12-26 18:01
Do I need to install p5.js or something else cuz i have no idea about this thing. Would be great if you provide some resources

**Comment by smaranjitghose** [comment] 2020-12-26 18:44
> Do I need to install p5.js or something else cuz i have no idea about this thing. Would be great if you provide some resources @smaranjitghose

You can have a look at "The Coding Train" [youtube](https://www.youtube.com/watch?v=yPWkPOfnGsw) channel by Dr. Daniel Shiffman. He has an entire playlist on it

**Comment by bhoomika07** [comment] 2020-12-28 11:41
I am interested in resolving this issue. A swoc participant.

**Comment by carbseater** [comment] 2021-01-03 15:19
![design](https://user-images.githubusercontent.com/59422042/103482114-e2646c80-4e04-11eb-839a-7942fd886e73.png)
Just wanted to know that will this layout fulfill the requirements ? If yes then assign me again so that i could start working.

**Comment by ashuvssut** [comment] 2021-01-03 21:42
Hello @smaranjitghose ,  I was working on this issue from last 2 days and today I completed it. I was facing many problems caused by existing CSS. Solving them took me too much time. Therefore I was unsure if I could submit my PR on time. I did't want to get unassigned. That's why I did not asked to assign me when carbseater was unassigned. I am sorry for that.

I made a lot of changes.
So Please consider allowing me to submit my PR.

Below given is the  screenshot of my work:
![image](https://user-images.githubusercontent.com/60546840/103489453-7d3f5580-4dc9-11eb-92e5-833a28e2a6f2.png)

**Closed** 2021-01-08 09:41 UTC
Labels: DWOC

**Comment by ashuvssut** [comment] 2021-01-08 10:27
Sir, this is an irrelevant comment,

Sir, I have contributed resolving issues that did not had any level tag. There was only one issue tagged with level-4. 

I did not receive points in DWoC for Those PRs which were merged successfully and did not have a level tag.

Is their any way to claim those DWoC points?

This issue also didn't have any level tag

**Comment by smaranjitghose** [comment] 2021-01-08 10:37
> Sir, this is an irrelevant comment,
> 
> Sir, I have contributed resolving issues that did not had any level tag. There was only one issue tagged with level-4.
> 
> I did not receive points in DWoC for Those PRs which were merged successfully and did not have a level tag.
> 
> Is their any way to claim those DWoC points?
> 
> This issue also doesn't have any level tag
> 
> -- ( I am a DWoC and SWoC participant)

__Done__

**Comment by carbseater** [comment] 2021-01-08 10:46
> Sir, this is an irrelevant comment,
> 
> Sir, I have contributed resolving issues that did not had any level tag. There was only one issue tagged with level-4.
> 
> I did not receive points in DWoC for Those PRs which were merged successfully and did not have a level tag.
> 
> Is their any way to claim those DWoC points?
> 
> This issue also doesn't have any level tag
> 
> -- ( I am a DWoC and SWoC participant)

Hey @ashuvssut how can we see our dwoc points ? can you drop the link here. Thanks

**Comment by ashuvssut** [comment] 2021-01-08 10:54
https://devscript.tech/woc/leaderboard

@carbseater join DWoC Discord server today😊 to check regular updates from the announcements channel in that server

**Comment by ashuvssut** [comment] 2021-01-08 10:57
> > Sir, this is an irrelevant comment,
> > Sir, I have contributed resolving issues that did not had any level tag. There was only one issue tagged with level-4.
> > I did not receive points in DWoC for Those PRs which were merged successfully and did not have a level tag.
> > Is their any way to claim those DWoC points?
> > This issue also doesn't have any level tag
> > -- ( I am a DWoC and SWoC participant)
> 
> **Done**

thankyou sir
