### ISSUE TITLE
Update the Open Source Section

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#297] opened 2020-12-27 10:29 UTC
Include Cards for Script Winter of Code and DevScript Winter of Code

**Comment by satyampandeygit** [comment] 2020-12-27 10:57
I want to do this kindly assign me this

**Comment by smriti1313** [comment] 2020-12-28 06:29
Hi, Can i work on it too? I am really excited to work on this project. Thank you

**Comment by Utkarshn10** [comment] 2020-12-28 06:52
I would like to work on this issue. I am a Swoc participant.

**Comment by satyampandeygit** [comment] 2020-12-29 06:56
The issue is resolved in PR #306

**Closed** 2020-12-30 07:09 UTC
Labels: SWoC2021
